# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_window(object):
    def setupUi(self, window):
        window.setObjectName("window")
        window.resize(1081, 624)
        self.shot = QtWidgets.QPushButton(window)
        self.shot.setGeometry(QtCore.QRect(620, 420, 91, 31))
        self.shot.setObjectName("shot")
        self.updata = QtWidgets.QPushButton(window)
        self.updata.setGeometry(QtCore.QRect(880, 20, 81, 31))
        self.updata.setObjectName("updata")
        self.line = QtWidgets.QFrame(window)
        self.line.setGeometry(QtCore.QRect(760, 0, 20, 621))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label1 = QtWidgets.QLabel(window)
        self.label1.setGeometry(QtCore.QRect(300, 60, 161, 16))
        self.label1.setObjectName("label1")
        self.show = QtWidgets.QLabel(window)
        self.show.setGeometry(QtCore.QRect(10, 100, 561, 501))
        self.show.setObjectName("show")
        self.det = QtWidgets.QPushButton(window)
        self.det.setGeometry(QtCore.QRect(620, 340, 91, 41))
        self.det.setObjectName("det")
        self.uploadimg = QtWidgets.QLabel(window)
        self.uploadimg.setGeometry(QtCore.QRect(850, 100, 151, 141))
        self.uploadimg.setText("")
        self.uploadimg.setObjectName("uploadimg")
        self.re1 = QtWidgets.QLabel(window)
        self.re1.setGeometry(QtCore.QRect(790, 380, 92, 112))
        self.re1.setFrameShape(QtWidgets.QFrame.Box)
        self.re1.setObjectName("re1")
        self.re2 = QtWidgets.QLabel(window)
        self.re2.setGeometry(QtCore.QRect(880, 380, 92, 112))
        self.re2.setFrameShape(QtWidgets.QFrame.Box)
        self.re2.setObjectName("re2")
        self.re3 = QtWidgets.QLabel(window)
        self.re3.setGeometry(QtCore.QRect(970, 380, 92, 112))
        self.re3.setFrameShape(QtWidgets.QFrame.Box)
        self.re3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.re3.setWordWrap(False)
        self.re3.setObjectName("re3")
        self.re4 = QtWidgets.QLabel(window)
        self.re4.setGeometry(QtCore.QRect(790, 490, 92, 112))
        self.re4.setFrameShape(QtWidgets.QFrame.Box)
        self.re4.setObjectName("re4")
        self.re5 = QtWidgets.QLabel(window)
        self.re5.setGeometry(QtCore.QRect(880, 490, 92, 112))
        self.re5.setFrameShape(QtWidgets.QFrame.Box)
        self.re5.setObjectName("re5")
        self.label = QtWidgets.QLabel(window)
        self.label.setGeometry(QtCore.QRect(290, 550, 141, 41))
        self.label.setObjectName("label")
        self.datadet = QtWidgets.QPushButton(window)
        self.datadet.setGeometry(QtCore.QRect(890, 310, 81, 41))
        self.datadet.setObjectName("datadet")
        self.label_2 = QtWidgets.QLabel(window)
        self.label_2.setGeometry(QtCore.QRect(970, 490, 92, 112))
        self.label_2.setFrameShape(QtWidgets.QFrame.Box)
        self.label_2.setObjectName("label_2")

        self.retranslateUi(window)
        QtCore.QMetaObject.connectSlotsByName(window)

    def retranslateUi(self, window):
        _translate = QtCore.QCoreApplication.translate
        window.setWindowTitle(_translate("window", "319 PCA人脸识别系统"))
        self.shot.setText(_translate("window", "拍照"))
        self.updata.setText(_translate("window", "上传照片"))
        self.label1.setText(_translate("window", "请把头像移到正中"))
        self.show.setText(_translate("window", "显示照片"))
        self.det.setText(_translate("window", "人脸识别"))
        self.re1.setText(_translate("window", "TextLabel"))
        self.re2.setText(_translate("window", "TextLabel"))
        self.re3.setText(_translate("window", "TextLabel"))
        self.re4.setText(_translate("window", "TextLabel"))
        self.re5.setText(_translate("window", "TextLabel"))
        self.label.setText(_translate("window", "TextLabel"))
        self.datadet.setText(_translate("window", "识别"))
        self.label_2.setText(_translate("window", "TextLabel"))
